### ISSUE TITLE
Logout instead of lockscreen

### ISSUE THREAD

**Issue by sirtoobii** [home-sweet-gnome/dash-to-panel#1002]
Probably a new gnome-shell version caused the following problem: As long dash-to-panel is active, locking the screen with either [Super]+L or through the menu, terminates the user session. Other extensions work fine.

**Linux distribution and version**
Debian bullseye/sid, Kernel: 5.6.0-1-amd64

**GNOME Shell version**
3.36.2

**Dash-to-Panel version**
Unable to see, settings are not available (however, seems to be the newest version available on extensions.gnome.org)
When clicking on the gear icon the following messages appear in syslog:
```
May 14 10:43:38 debianMTB org.gnome.tweaks.desktop[9779]: Traceback (most recent call last):
May 14 10:43:38 debianMTB org.gnome.tweaks.desktop[9779]:   File "/usr/lib/python3/dist-packages/gtweak/tweaks/tweak_group_shell_extensions.py", line 162, in _on_configure_clicked
May 14 10:43:38 debianMTB org.gnome.tweaks.desktop[9779]:     execute_subprocess(['gnome-shell-extension-prefs', uuid], block=False)
May 14 10:43:38 debianMTB org.gnome.tweaks.desktop[9779]:   File "/usr/lib/python3/dist-packages/gtweak/utils.py", line 105, in execute_subprocess
May 14 10:43:38 debianMTB org.gnome.tweaks.desktop[9779]:     p = subprocess.Popen(
May 14 10:43:38 debianMTB org.gnome.tweaks.desktop[9779]:   File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
May 14 10:43:38 debianMTB org.gnome.tweaks.desktop[9779]:     self._execute_child(args, executable, preexec_fn, close_fds,
May 14 10:43:38 debianMTB org.gnome.tweaks.desktop[9779]:   File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
May 14 10:43:38 debianMTB org.gnome.tweaks.desktop[9779]:     raise child_exception_type(errno_num, err_msg, err_filename)
May 14 10:43:38 debianMTB org.gnome.tweaks.desktop[9779]: FileNotFoundError: [Errno 2] No such file or directory: 'gnome-shell-extension-prefs'
```
However, this issue seems to unrelated since the settings are not available of all extensions.

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Comment by charlesg99** [comment]
Hello, please see #976 and #981. Thanks!
