### ISSUE TITLE
Segfault when pressing numeric shortcut to open app from panel right after unlocking GNOME

### ISSUE THREAD

**Issue by 190n** [home-sweet-gnome/dash-to-panel#2106]
**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session. (done, and it also does not occur when all extensions are disabled)
- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem. (done, but there were no errors)
- Search existing opened and closed issues to see if the problem has already been reported. (done)

**Describe the bug**
When I press Super+8 to open an application from my panel right after unlocking GNOME (I've been testing by spamming the key combo right after pressing on the fingerprint reader), it segfaults.

It seems on this line (`src/core/keybindings.c:1882`):

```c
invoke_handler (display, binding->handler, window, event, binding);
```

`binding->handler->func` is set to `0x7f443d6ad2a0`, which is the address of the global struct `ffi_type_pointer`, not a function pointer. This gets called inside `invoke_handler`, on `src/core/keybindings.c:1786`, and it executed the struct contents as code until it happened to segfault.

<details><summary>Full stack trace</summary>
<pre>
#0  0x00007f443d6ad2a0 in ffi_type_pointer () from /lib64/libffi.so.8
#1  0x00007f443e0cc21e in process_event (display=display@entry=0x55fe3dc0e7d0, window=window@entry=0x55fe45cb5ee0, event=event@entry=0x7f43d8004b00) at ../src/core/keybindings.c:1882
#2  0x00007f443e0cdaae in process_key_event (display=0x55fe3dc0e7d0, window=<optimized out>, event=0x7f43d8004b00) at ../src/core/keybindings.c:2154
#3  meta_keybindings_process_event (display=0x55fe3dc0e7d0, window=<optimized out>, event=0x7f43d8004b00) at ../src/core/keybindings.c:2191
#4  meta_display_handle_event (display=0x55fe3dc0e7d0, event=0x7f43d8004b00, event_actor=<optimized out>) at ../src/core/events.c:398
#5  event_callback (event=0x7f43d8004b00, event_actor=<optimized out>, data=0x55fe3dc0e7d0) at ../src/core/events.c:486
#6  0x00007f443e49e7eb in _clutter_event_process_filters (event=0x7f43d8004b00, event_actor=0x55fe3dbc3720) at ../clutter/clutter/clutter-event.c:1302
#7  0x00007f443e4c226d in clutter_stage_handle_event (stage=0x55fe3dbc3720, event=0x7f43d8004b00) at ../clutter/clutter/clutter-main.c:530
#8  0x00007f443e077603 in dispatch_clutter_event (backend=0x55fe3d891a20) at ../src/backends/meta-backend.c:1133
#9  0x00007f443e0776f1 in clutter_source_dispatch (source=0x55fe3db97780, callback=<optimized out>, user_data=<optimized out>) at ../src/backends/meta-backend.c:1177
#10 0x00007f443e74368c in g_main_dispatch (context=0x55fe3d72c5e0) at ../glib/gmain.c:3344
#11 g_main_context_dispatch_unlocked (context=0x55fe3d72c5e0) at ../glib/gmain.c:4152
#12 0x00007f443e7a4788 in g_main_context_iterate_unlocked.isra.0 (context=0x55fe3d72c5e0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4217
#13 0x00007f443e749647 in g_main_loop_run (loop=0x55fe3dc3fd80) at ../glib/gmain.c:4419
#14 0x00007f443e0d292a in meta_context_run_main_loop (context=<optimized out>, error=0x7ffc37707800) at ../src/core/meta-context.c:523
#15 0x00007f443d6aa056 in ffi_call_unix64 () at ../src/x86/unix64.S:104
#16 0x00007f443d6a66a0 in ffi_call_int (cif=cif@entry=0x55fe3dd05ce0, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>, closure=closure@entry=0x0) at ../src/x86/ffi64.c:673
#17 0x00007f443d6a94ee in ffi_call (cif=0x55fe3dd05ce0, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>) at ../src/x86/ffi64.c:710
#18 0x00007f443e595eee in Gjs::Function::invoke (this=0x55fe3dd05cc0, context=0x55fe3d758c10, args=..., this_obj=..., r_value=<optimized out>) at ../gi/function.cpp:1056
#19 0x00007f443e597313 in Gjs::Function::call (context=0x55fe3d758c10, js_argc=<optimized out>, vp=<optimized out>) at ../gi/function.cpp:1238
#20 0x00007f443c87cb64 in CallJSNative (args=..., reason=js::CallReason::Call, native=0x7f443e597230 <Gjs::Function::call(JSContext*, unsigned int, JS::Value*)>, cx=0x55fe3d758c10) at /usr/src/debug/mozjs115-115.7.0-1.fc40.x86_64/vm/Interpreter.cpp:486
#21 js::InternalCallOrConstruct (cx=0x55fe3d758c10, args=..., construct=<optimized out>, reason=js::CallReason::Call) at /usr/src/debug/mozjs115-115.7.0-1.fc40.x86_64/vm/Interpreter.cpp:566
#22 0x00007f443c886286 in InternalCall (reason=<optimized out>, args=..., cx=<optimized out>) at /usr/src/debug/mozjs115-115.7.0-1.fc40.x86_64/vm/Interpreter.cpp:647
#23 js::CallFromStack (reason=<optimized out>, args=..., cx=<optimized out>) at /usr/src/debug/mozjs115-115.7.0-1.fc40.x86_64/vm/Interpreter.cpp:652
#24 js::Interpret (cx=0x55fe3d758c10, state=...) at /usr/src/debug/mozjs115-115.7.0-1.fc40.x86_64/vm/Interpreter.cpp:3395
#25 0x00007f443c87c523 in MaybeEnterInterpreterTrampoline (state=..., cx=0x55fe3d758c10) at /usr/src/debug/mozjs115-115.7.0-1.fc40.x86_64/vm/Interpreter.cpp:400
#26 js::RunScript (cx=cx@entry=0x55fe3d758c10, state=...) at /usr/src/debug/mozjs115-115.7.0-1.fc40.x86_64/vm/Interpreter.cpp:458
#27 0x00007f443c87ca67 in js::InternalCallOrConstruct (cx=cx@entry=0x55fe3d758c10, args=..., construct=construct@entry=js::NO_CONSTRUCT, reason=<optimized out>) at /usr/src/debug/mozjs115-115.7.0-1.fc40.x86_64/vm/Interpreter.cpp:612
#28 0x00007f443c87cedd in InternalCall (reason=<optimized out>, args=..., cx=0x55fe3d758c10) at /usr/src/debug/mozjs115-115.7.0-1.fc40.x86_64/vm/Interpreter.cpp:647
#29 js::Call (cx=0x55fe3d758c10, fval=..., thisv=..., args=..., rval=..., reason=<optimized out>) at /usr/src/debug/mozjs115-115.7.0-1.fc40.x86_64/vm/Interpreter.cpp:679
#30 0x00007f443c901bd8 in JS::Call (cx=0x55fe3d758c10, thisv=..., fval=fval@entry=..., args=..., rval=..., rval@entry=...) at /usr/src/debug/mozjs115-115.7.0-1.fc40.x86_64/vm/CallAndConstruct.cpp:117
#31 0x00007f443e5cab02 in JS::Call (cx=<optimized out>, thisv=..., funObj=..., args=..., rval=...) at /usr/include/mozjs-115/js/RootingAPI.h:1219
#32 GjsContextPrivate::run_main_loop_hook (this=0x55fe3d74f610) at ../gjs/context.cpp:1491
#33 0x00007f443e5d1f8f in GjsContextPrivate::eval_module (this=0x55fe3d74f610, identifier=0x55fe3da17cf0 "resource:///org/gnome/shell/ui/init.js", exit_status_p=0x7ffc3770819b "", error=0x7ffc377081a0) at ../gjs/context.cpp:1608
#34 gjs_context_eval_module (js_context=<optimized out>, identifier=0x55fe3da17cf0 "resource:///org/gnome/shell/ui/init.js", exit_code=0x7ffc3770819b "", error=0x7ffc377081a0) at ../gjs/context.cpp:1387
#35 0x00007f443e5d21b9 in gjs_context_eval_module_file (js_context=js_context@entry=0x55fe3d74f7b0, filename=filename@entry=0x55fe3cb46640 "resource:///org/gnome/shell/ui/init.js", exit_status_p=exit_status_p@entry=0x7ffc3770819b "", 
    error=error@entry=0x7ffc377081a0) at ../gjs/context.cpp:1692
#36 0x000055fe3cb45036 in main (argc=<optimized out>, argv=<optimized out>) at ../src/main.c:708
</pre>
</details>

I've saved a core dump too in case we need any more info from that.

**Linux distribution and version**
Fedora Silverblue 40.20240512.0

**GNOME Shell version**
46.1, Wayland

**Dash-to-Panel version**
62

**Where was Dash-to-Panel installed from?**
extensions.gnome.org

**Screenshots / Video captures**
If applicable, add screenshots or a link to a video capture to help explain your problem.

**Additional Info**

**Comment by charlesg99** [comment]
I can't reproduce this on gnome-shell 47
