### ISSUE TITLE
Gnome-Shell crash when launching 5 windows of the same app with v17

### ISSUE THREAD

**Issue by P4E** [home-sweet-gnome/dash-to-panel#552]
Here is a backtrace. Firefox is launching a saved session with a few windows.
No crash when Dash-to-panel is deactivated.

```[Thread 0x7f630ffff700 (LWP 24790) exited]
[New Thread 0x7f630ffff700 (LWP 24804)]
[New Thread 0x7f631e47f700 (LWP 24805)]
[Thread 0x7f630ffff700 (LWP 24804) exited]
[Detaching after vfork from child process 24806]
[New Thread 0x7f630ffff700 (LWP 24807)]
[Thread 0x7f631e47f700 (LWP 24805) exited]

Thread 1 "gnome-shell" received signal SIGTRAP, Trace/breakpoint trap.
0x00007f6385d319f5 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#0  0x00007f6385d319f5 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f6385d32a9d in g_log_default_handler () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x0000561d8a076b05 in  ()
#3  0x00007f6385d32cef in g_logv () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f6385d32edf in g_log () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f6385f5722a in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#6  0x00007f6385f5787c in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#7  0x00007f6385f5b4af in g_settings_get_value () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#8  0x00007f6385f5c32b in g_settings_get_string () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#9  0x00007f638434e8ee in ffi_call_unix64 () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#10 0x00007f638434e2bf in ffi_call () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#11 0x00007f63854ab819 in gjs_invoke_c_function(JSContext*, Function*, JS::HandleObject, JS::HandleValueArray const&, mozilla::Maybe<JS::MutableHandle<JS::Value> >, GIArgument*) (context=0x561d8b81e5e0, function=0x561d8bdb5860, obj=..., args=..., js_rval=..., r_value=0x0) at gi/function.cpp:1096
        in_arg_cvalues = 0x7ffc7b309c70
        out_arg_cvalues = 0x7ffc7b309c30
        inout_original_arg_cvalues = 0x7ffc7b309c10
        ffi_arg_pointers = 0x7ffc7b309c50
        return_value = {v_boolean = 2066784568, v_int8 = 56 '8', v_uint8 = 56 '8', v_int16 = -24264, v_uint16 = 41272, v_int32 = 2066784568, v_uint32 = 2066784568, v_int64 = 140722375270712, v_uint64 = 140722375270712, v_float = 9.17114152e+35, v_double = 6.9526091222438586e-310, v_short = -24264, v_ushort = 41272, v_int = 2066784568, v_uint = 2066784568, v_long = 140722375270712, v_ulong = 140722375270712, v_ssize = 140722375270712, v_size = 140722375270712, v_string = 0x7ffc7b30a138 "\310R|fc\177\373\377\200\020\261\064c\177\376\377\260\"Ifc\177\376\377\220a\252fc\177\376\377@v\277\065c\177\376\377\200\217\354dc\177\373\377", v_pointer = 0x7ffc7b30a138}
        return_value_p = 0x7ffc7b309d68
        return_gargument = {v_boolean = 2066784520, v_int8 = 8 '\b', v_uint8 = 8 '\b', v_int16 = -24312, v_uint16 = 41224, v_int32 = 2066784520, v_uint32 = 2066784520, v_int64 = 140722375270664, v_uint64 = 140722375270664, v_float = 9.17110349e+35, v_double = 6.9526091222414871e-310, v_short = -24312, v_ushort = 41224, v_int = 2066784520, v_uint = 2066784520, v_long = 140722375270664, v_ulong = 140722375270664, v_ssize = 140722375270664, v_size = 140722375270664, v_string = 0x7ffc7b30a108 "\200\020\261\064c\177\376\377\310R|fc\177\373\377\250\241\060{\374\177", v_pointer = 0x7ffc7b30a108}
        processed_c_args = 2 '\002'
        gi_argc = 1 '\001'
        gi_arg_pos = <optimized out>
        c_argc = 2 '\002'
        c_arg_pos = <optimized out>
        js_arg_pos = <optimized out>
        can_throw_gerror = false
        did_throw_gerror = false
        local_error = 0x0
        failed = false
        postinvoke_release_failed = <optimized out>
        is_method = <optimized out>
        is_object_method = true
        return_info = {dummy1 = 18, dummy2 = 2147483647, dummy3 = 0x561d8b44d420, dummy4 = 0x561d8bdd7190, dummy5 = 0x561d8bc2b360, dummy6 = 232352, dummy7 = 0, padding = {0x0, 0x0, 0x0, 0x0}}
        return_tag = GI_TYPE_TAG_UTF8
        return_values = {<JS::Rooted<JS::GCVector<JS::Value, 8, js::TempAllocPolicy> >> = {<js::RootedBase<JS::GCVector<JS::Value, 8, js::TempAllocPolicy>, JS::Rooted<JS::GCVector<JS::Value, 8, js::TempAllocPolicy> > >> = {<js::MutableWrappedPtrOperations<JS::GCVector<JS::Value, 8, js::TempAllocPolicy>, JS::Rooted<JS::GCVector<JS::Value, 8, js::TempAllocPolicy> > >> = {<js::WrappedPtrOperations<JS::GCVector<JS::Value, 8, js::TempAllocPolicy>, JS::Rooted<JS::GCVector<JS::Value, 8, js::TempAllocPolicy> > >> = {<No data fields>}, <No data fields>}, <No data fields>}, stack = 0x561d8b81e648, prev = 0x7ffc7b30a708, ptr = {tracer = 0x7f63854a36f0 <JS::StructGCPolicy<JS::GCVector<JS::Value, 8ul, js::TempAllocPolicy> >::trace(JSTracer*, JS::GCVector<JS::Value, 8ul, js::TempAllocPolicy>*, char const*)>, storage = {vector = {<js::TempAllocPolicy> = {cx_ = 0x561d8b81e5e0}, static kElemIsPod = false, static kMaxInlineBytes = 992, static kInlineCapacity = 8, mBegin = 0x7ffc7b309f78, mLength = 0, mTail = {<mozilla::Vector<JS::Value, 8, js::TempAllocPolicy>::CapacityAndReserved> = {mCapacity = 8}, mBytes = "\033\000\000\000\000\000\000\000\220\237\060{\374\177\000\000\231k\212\202c\177\000\000Р0{\374\177\000\000<h\246\202c\177\000\000L\000\000\000\000\000\000\000(\241\060{\374\177\000\000(\241\060{\374\177\000"}, static sMaxInlineStorage = <optimized out>}}}}, <No data fields>}
        next_rval = 0 '\000'
        __PRETTY_FUNCTION__ = "bool gjs_invoke_c_function(JSContext*, Function*, JS::HandleObject, const JS::HandleValueArray&, mozilla::Maybe<JS::MutableHandle<JS::Value> >, GIArgument*)"
#12 0x00007f63854acf96 in function_call(JSContext*, unsigned int, JS::Value*) (context=0x561d8b81e5e0, js_argc=1, vp=0x7ffc7b30a100) at /usr/include/mozjs-60/js/RootingAPI.h:1128
        object = {<js::RootedBase<JSObject*, JS::Rooted<JSObject*> >> = {<js::MutableWrappedPtrOperations<JSObject*, JS::Rooted<JSObject*> >> = {<js::WrappedPtrOperations<JSObject*, JS::Rooted<JSObject*> >> = {<No data fields>}, <No data fields>}, <No data fields>}, stack = 0x561d8b81e600, prev = 0x7ffc7b30a728, ptr = 0x7f6334b11080}
        callee = {<js::RootedBase<JSObject*, JS::Rooted<JSObject*> >> = {<js::MutableWrappedPtrOperations<JSObject*, JS::Rooted<JSObject*> >> = {<js::WrappedPtrOperations<JSObject*, JS::Rooted<JSObject*> >> = {<No data fields>}, <No data fields>}, <No data fields>}, stack = 0x561d8b81e600, prev = 0x7ffc7b30a010, ptr = 0x7f63664922b0}
        success = <optimized out>
        priv = 0x561d8bdb5860
        retval = {<js::RootedBase<JS::Value, JS::Rooted<JS::Value> >> = {<js::MutableWrappedPtrOperations<JS::Value, JS::Rooted<JS::Value> >> = {<js::WrappedPtrOperations<JS::Value, JS::Rooted<JS::Value> >> = {<No data fields>}, <No data fields>}, <No data fields>}, stack = 0x561d8b81e640, prev = 0x7ffc7b30a6c0, ptr = {data = {asBits = 18444914486360932352, debugView = {payload47 = 0, tag = JSVAL_TAG_UNDEFINED}, s = {payload = {i32 = 0, u32 = 0, why = JS_ELEMENTS_HOLE}}, asDouble = -nan(0x9800000000000), asPtr = 0xfff9800000000000, asWord = 18444914486360932352, asUIntPtr = 18444914486360932352}}}
#13 0x000013c8624a7025 in  ()
#14 0x00007ffc7b30a1a8 in  ()
#15 0x00007ffc7b30a0e0 in  ()
#16 0x0000000000000000 in  ()
A debugging session is active.

	Inferior 1 [process 7566] will be detached.

Quit anyway? (y or n) [answered Y; input not from terminal]
[Inferior 1 (process 7566) detached]```

**Comment by charlesg99** [comment]
Could you please give a bit more information about your system (gnome-shell version, xorg/wayland, distro)? I tried restoring a firefox session and it works without issue. Thanks!

**Comment by P4E** [comment]
Sorry I posted a bit in a rush.

Debian Unstable up-to-date
Gnome Shell 3.30.2 vanilla (no other extension)
Firefox 64.0
Linux 4.19.0

The issue occurs on both Xorg and Wayland.

**Comment by charlesg99** [comment]
I can't reproduce this on debian sid (all versions you mentioned). Do you by chance see a js error in the gnome-shell logs when this occurs? Anything else special with your config or installation? Thanks!

**Comment by charlesg99** [comment]
Ha yes, thanks! I will fix that now.

**Comment by charlesg99** [comment]
Could you please pull/install master again to see if that fixes it? Thanks again for your investigation!

**Comment by P4E** [comment]
Yes, it's fixed.
No worries, thank you for making this great extension :)

**Comment by ccaspers** [comment]
I am experiencing the same right now. Any estimation, when v18 will be available in the official repositories?

**Comment by LeleDev** [comment]
same problem here... any ETA?

**Comment by ccaspers** [comment]
@LeleDev I gave up and installed the latest from Github manually. It's not hard, and solves the Issue for now.
